import { ProviderViewModel } from "@/types/provider";

export const Providers: ProviderViewModel[] = [
  {
    id: 1,
    name: "Alex Johnson",
    profession: "Electrician",
    categoryName: "Electrician",
    remoteService: false,
    rating: 4.8,
    reviews: 150,
    bio: "Experienced electrician specializing in household repairs and lighting.",
    avatar: require("@/assets/images/avatar-placeholder.png"),
    cover: require("@/assets/images/loginbg.png"),
    location: { latitude: 37.7749, longitude: -122.4194 },
    distance: 10,
    portfolio: [
      {
        id: "1",
        image: require("@/assets/images/react-logo.png"),
        caption: "Wiring work",
      },
      {
        id: "2",
        image: require("@/assets/images/splash-icon.png"),
        caption: "Panel install",
      },
    ],
    services: [
      {
        id: "elec-1",
        name: "Lighting Installation",
        description:
          "Complete lighting installation service including fixtures and wiring",
        price: "75000",
        availability: "Available weekdays",
      },
      {
        id: "elec-2",
        name: "Electrical Repairs",
        description: "General electrical repairs and maintenance",
        price: "50000",
        availability: "Available anytime",
      },
    ],
    reviewItems: [
      {
        id: "1",
        clientName: "Sarah P.",
        rating: 5,
        comment: "Alex's work was exceptional and timely. Highly recommend!",
        date: "2023-10-15T14:30:00Z",
        serviceName: "Lighting Installation",
        serviceId: "elec-1",
      },
      {
        id: "2",
        clientName: "John D.",
        rating: 4,
        comment: "Professional and efficient service. Will hire again.",
        date: "2023-09-28T09:15:00Z",
        serviceName: "Electrical Repairs",
        serviceId: "elec-2",
        response: {
          text: "Thank you for your kind feedback! Looking forward to serving you again.",
          date: "2023-09-29T10:20:00Z",
        },
      },
    ],
    pricing: "50000 - 150000 CFA",
  },
  {
    id: 2,
    name: "Sarah Doe",
    profession: "Tailor",
    categoryName: "Tailor",
    remoteService: false,
    rating: 5,
    reviews: 120,
    bio: "Expert tailor specializing in custom clothing and alterations.",
    avatar: require("@/assets/images/avatar-placeholder.png"),
    cover: require("@/assets/images/favicon.png"),
    location: { latitude: 34.0522, longitude: -118.2437 },
    distance: 15,
    portfolio: [
      {
        id: "3",
        image: require("@/assets/images/react-logo.png"),
        caption: "Custom dress design",
      },
    ],
    services: [
      {
        id: "tail-1",
        name: "Custom Clothing",
        description: "Made-to-measure custom clothing design and creation",
        price: "100000",
      },
      {
        id: "tail-2",
        name: "Alterations",
        description: "Clothing alterations and repairs",
        price: "20000",
      },
    ],
    reviewItems: [
      {
        id: "3",
        clientName: "Emily R.",
        rating: 5,
        comment: "Sarah's tailoring skills are unmatched!",
        date: "2023-08-12T11:00:00Z",
        serviceName: "Custom Clothing",
        serviceId: "tail-1",
      },
    ],
    pricing: "20000 - 100000 CFA",
  },
  {
    id: 3,
    name: "John Fixit",
    profession: "Plumber",
    categoryName: "Plumber",
    remoteService: false,
    rating: 2.6,
    reviews: 90,
    bio: "Reliable plumber for all your household needs.",
    avatar: require("@/assets/images/avatar-placeholder.png"),
    cover: require("@/assets/images/favicon.png"),
    location: { latitude: 40.7128, longitude: -74.006 },
    distance: 50,
    portfolio: [
      {
        id: "4",
        image: require("@/assets/images/splash-icon.png"),
        caption: "Pipe repair",
      },
    ],
    services: [
      {
        id: "plumb-1",
        name: "Leak Repairs",
        description: "Fixing leaks in pipes and faucets",
        price: "50000",
      },
      {
        id: "plumb-2",
        name: "Pipe Installation",
        description: "Installing new pipes and plumbing systems",
        price: "100000",
      },
    ],
    reviewItems: [
      {
        id: "4",
        clientName: "Mark T.",
        rating: 4,
        comment: "John fixed my plumbing issues quickly and efficiently.",
        date: "2023-07-20T16:45:00Z",
        serviceName: "Leak Repairs",
        serviceId: "plumb-1",
      },
    ],
    pricing: "50000 - 100000 CFA",
  },
  {
    id: 4,
    name: "Catering Co.",
    profession: "Caterer",
    categoryName: "Caterer",
    remoteService: false,
    rating: 3.9,
    reviews: 200,
    bio: "Delicious catering services for all occasions.",
    avatar: require("@/assets/images/avatar-placeholder.png"),
    cover: require("@/assets/images/favicon.png"),
    location: { latitude: 41.8781, longitude: -87.6298 },
    distance: 30,
    portfolio: [
      {
        id: "5",
        image: require("@/assets/images/react-logo.png"),
        caption: "Wedding catering",
      },
    ],
    services: [
      {
        id: "cater-1",
        name: "Event Catering",
        description: "Full-service catering for events and parties",
        price: "500000",
      },
      {
        id: "cater-2",
        name: "Custom Menus",
        description: "Creating custom menus tailored to your event",
        price: "300000",
      },
    ],
    reviewItems: [
      {
        id: "5",
        clientName: "Anna K.",
        rating: 5,
        comment: "The food was amazing, and the service was top-notch!",
        date: "2023-06-10T13:30:00Z",
        serviceName: "Event Catering",
        serviceId: "cater-1",
      },
    ],
    pricing: "300000 - 500000 CFA",
  },
  {
    id: 5,
    name: "Graphic Guru",
    profession: "Designer",
    categoryName: "Design",
    remoteService: true,
    rating: 4,
    reviews: 200,
    bio: "Creative graphic designer specializing in branding and digital art.",
    avatar: require("@/assets/images/avatar-placeholder.png"),
    cover: require("@/assets/images/favicon.png"),
    location: { latitude: 41.8781, longitude: -87.6298 },
    distance: 50,
    portfolio: [
      {
        id: "6",
        image: require("@/assets/images/react-logo.png"),
        caption: "Wedding catering",
      },
    ],
    services: [
      {
        id: "design-1",
        name: "Web Designing",
        description: "Designing responsive and visually appealing websites",
        price: "500000",
      },
      {
        id: "design-2",
        name: "Logo Design",
        description: "Creating unique and professional logos",
        price: "300000",
      },
    ],
    reviewItems: [
      {
        id: "6",
        clientName: "Anna K.",
        rating: 5,
        comment: "The design was both creative and professional.",
        date: "2023-05-15T10:00:00Z",
        serviceName: "Logo Design",
        serviceId: "design-2",
      },
    ],
    pricing: "300000 - 500000 CFA",
  },
];
